input_dir : "./data/ogbn_arxiv/"
grap_name : "ogbn-arxiv"
in_channels : 128
hidden_channels : 256
out_channels : 40
num_layers : 3
dropout : 0.5
lr : 0.01
weight_decay : 0
num_epochs : 200
random_seed : 0