input_dir : "./dataset/ogbn_products_new/"
graph_name : "products"
model_name : "sage"
in_channels : 100
hidden_channels : 128
out_channels : 47
num_layers : 3
dropout : 0.5
lr : 0.01
weight_decay : 0.0
num_epochs : 20
random_seed : 0
